#!/bin/zsh

##################################################################################################
#       444444444   222222222222222    
#      4::::::::4  2:::::::::::::::22  
#     4:::::::::4  2::::::222222:::::2 
#    4::::44::::4  2222222     2:::::2 
#   4::::4 4::::4              2:::::2 
#  4::::4  4::::4              2:::::2 
# 4::::4   4::::4           2222::::2  
#4::::444444::::444    22222::::::22     by dlanotte
#4::::::::::::::::4  22::::::::222       888     888 888    d8b 888   
#4444444444:::::444 2:::::22222          888     888 888    Y8P 888       
#          4::::4  2:::::2               888     888 888        888          
#          4::::4  2:::::2               888     888 888888 888 888 .d8888b      
#          4::::4  2:::::2       222222  888     888 888    888 888 88K      
#        44::::::442::::::2222222:::::2  888     888 888    888 888 "Y8888b. 
#        4::::::::42::::::::::::::::::2  Y88b. .d88P Y88b.  888 888      X88 
#        444444444422222222222222222222   "Y88888P"   "Y888 888 888  88888P' 
##################################################################################################    

if ! defaults read -g AppleInterfaceStyle &> /dev/null; then
	echo "Change to Dark mode......";
    osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to not dark mode'
else
    echo "Dark Mode is already activated [✅]";
fi

if [ -d "$HOME/goinfre/.brew" ]; then
    echo "brew already installed [✅]";
else
    echo "Install Brew......";
    git clone --depth=1 https://github.com/Homebrew/brew ~/goinfre/.brew;
fi

export PATH="$HOME/goinfre/.brew/bin:$HOME/goinfre/.brew/sbin:$PATH"

