#!/bin/zsh

##################################################################################################
#       444444444   222222222222222    
#      4::::::::4  2:::::::::::::::22  
#     4:::::::::4  2::::::222222:::::2 
#    4::::44::::4  2222222     2:::::2 
#   4::::4 4::::4              2:::::2 
#  4::::4  4::::4              2:::::2 
# 4::::4   4::::4           2222::::2  
#4::::444444::::444    22222::::::22     by dlanotte
#4::::::::::::::::4  22::::::::222       888     888 888    d8b 888   
#4444444444:::::444 2:::::22222          888     888 888    Y8P 888       
#          4::::4  2:::::2               888     888 888        888          
#          4::::4  2:::::2               888     888 888888 888 888 .d8888b      
#          4::::4  2:::::2       222222  888     888 888    888 888 88K      
#        44::::::442::::::2222222:::::2  888     888 888    888 888 "Y8888b. 
#        4::::::::42::::::::::::::::::2  Y88b. .d88P Y88b.  888 888      X88 
#        444444444422222222222222222222   "Y88888P"   "Y888 888 888  88888P' 
##################################################################################################    

if [ -d "$HOME/goinfre/.Applications/Visual Studio Code.app/" ]; then
	clear;
elif [ -d "$HOME/goinfre/.brew/Caskroom/visual-studio-code" ]; then
	brew cleanup
	brew reinstall visual-studio-code
else
	brew cleanup
	brew install --cask visual-studio-code
fi

if [ -d "$HOME/goinfre/.Applications/Godot.app/" ]; then
	clear;
elif [ -d "$HOME/goinfre/.brew/Caskroom/godot" ]; then
	brew cleanup
	brew reinstall visual-studio-code
else
	brew cleanup
	brew install --cask godot
fi

if [ -d "$HOME/goinfre/.Applications/Postman.app/" ]; then
	clear;
elif [ -d "$HOME/goinfre/.brew/Caskroom/postman" ]; then
	brew cleanup
	brew reinstall postman
else
	brew cleanup
	brew install --cask postman
fi